// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package userclient

import (
	"context"

	"bookstore/user/rpc/user/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	UserExistReply = user.UserExistReply
	UserExistReq   = user.UserExistReq

	User interface {
		IsUserExist(ctx context.Context, in *UserExistReq, opts ...grpc.CallOption) (*UserExistReply, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) IsUserExist(ctx context.Context, in *UserExistReq, opts ...grpc.CallOption) (*UserExistReply, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.IsUserExist(ctx, in, opts...)
}
