// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	bookstoreFieldNames          = builder.RawFieldNames(&Bookstore{})
	bookstoreRows                = strings.Join(bookstoreFieldNames, ",")
	bookstoreRowsExpectAutoSet   = strings.Join(stringx.Remove(bookstoreFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	bookstoreRowsWithPlaceHolder = strings.Join(stringx.Remove(bookstoreFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	bookstoreModel interface {
		Insert(ctx context.Context, data *Bookstore) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Bookstore, error)
		FindOneByName(ctx context.Context, name string) (*Bookstore, error)
		Update(ctx context.Context, data *Bookstore) error
		Delete(ctx context.Context, id string) error
	}

	defaultBookstoreModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Bookstore struct {
		Id          string       `db:"id"`     // 书籍序列号
		Name        string       `db:"name"`   // 书籍名称
		Author      string       `db:"author"` // 书籍作者
		PublishDate sql.NullTime `db:"publish_date"`
		CreateTime  time.Time    `db:"create_time"`
		UpdateTime  time.Time    `db:"update_time"`
	}
)

func newBookstoreModel(conn sqlx.SqlConn) *defaultBookstoreModel {
	return &defaultBookstoreModel{
		conn:  conn,
		table: "`bookstore`",
	}
}

func (m *defaultBookstoreModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultBookstoreModel) FindOne(ctx context.Context, id string) (*Bookstore, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", bookstoreRows, m.table)
	var resp Bookstore
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBookstoreModel) FindOneByName(ctx context.Context, name string) (*Bookstore, error) {
	var resp Bookstore
	query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", bookstoreRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, name)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBookstoreModel) Insert(ctx context.Context, data *Bookstore) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, bookstoreRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.Name, data.Author, data.PublishDate)
	return ret, err
}

func (m *defaultBookstoreModel) Update(ctx context.Context, newData *Bookstore) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, bookstoreRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Name, newData.Author, newData.PublishDate, newData.Id)
	return err
}

func (m *defaultBookstoreModel) tableName() string {
	return m.table
}
