// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"bookstore/borrow/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/borrow/do",
				Handler: borrowHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/borrow/return",
				Handler: returnHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
