// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"bookstore/user/rpc/user/internal/logic"
	"bookstore/user/rpc/user/internal/svc"
	"bookstore/user/rpc/user/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) IsUserExist(ctx context.Context, in *user.UserExistReq) (*user.UserExistReply, error) {
	l := logic.NewIsUserExistLogic(ctx, s.svcCtx)
	return l.IsUserExist(in)
}
