// Code generated by goctl. DO NOT EDIT.
// Source: bookstore.proto

package bookstoreclient

import (
	"context"

	"bookstore/bookstore/rpc/bookstore"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FindBookReply = bookstore.FindBookReply
	FindBookReq   = bookstore.FindBookReq

	Bookstore interface {
		// 通过书籍名称查找书籍
		FindBookByName(ctx context.Context, in *FindBookReq, opts ...grpc.CallOption) (*FindBookReply, error)
	}

	defaultBookstore struct {
		cli zrpc.Client
	}
)

func NewBookstore(cli zrpc.Client) Bookstore {
	return &defaultBookstore{
		cli: cli,
	}
}

// 通过书籍名称查找书籍
func (m *defaultBookstore) FindBookByName(ctx context.Context, in *FindBookReq, opts ...grpc.CallOption) (*FindBookReply, error) {
	client := bookstore.NewBookstoreClient(m.cli.Conn())
	return client.FindBookByName(ctx, in, opts...)
}
