// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	shorturlFieldNames          = builder.RawFieldNames(&Shorturl{})
	shorturlRows                = strings.Join(shorturlFieldNames, ",")
	shorturlRowsExpectAutoSet   = strings.Join(stringx.Remove(shorturlFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	shorturlRowsWithPlaceHolder = strings.Join(stringx.Remove(shorturlFieldNames, "`shorturl`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheShorturlShorturlPrefix = "cache:shorturl:shorturl:"
)

type (
	shorturlModel interface {
		Insert(ctx context.Context, data *Shorturl) (sql.Result, error)
		FindOne(ctx context.Context, shorturl string) (*Shorturl, error)
		Update(ctx context.Context, data *Shorturl) error
		Delete(ctx context.Context, shorturl string) error
	}

	defaultShorturlModel struct {
		sqlc.CachedConn
		table string
	}

	Shorturl struct {
		Shorturl string `db:"shorturl"` // shorten key
		Url      string `db:"url"`
	}
)

func newShorturlModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultShorturlModel {
	return &defaultShorturlModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`shorturl`",
	}
}

func (m *defaultShorturlModel) Delete(ctx context.Context, shorturl string) error {
	shorturlShorturlKey := fmt.Sprintf("%s%v", cacheShorturlShorturlPrefix, shorturl)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `shorturl` = ?", m.table)
		return conn.ExecCtx(ctx, query, shorturl)
	}, shorturlShorturlKey)
	return err
}

func (m *defaultShorturlModel) FindOne(ctx context.Context, shorturl string) (*Shorturl, error) {
	shorturlShorturlKey := fmt.Sprintf("%s%v", cacheShorturlShorturlPrefix, shorturl)
	var resp Shorturl
	err := m.QueryRowCtx(ctx, &resp, shorturlShorturlKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `shorturl` = ? limit 1", shorturlRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, shorturl)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShorturlModel) Insert(ctx context.Context, data *Shorturl) (sql.Result, error) {
	shorturlShorturlKey := fmt.Sprintf("%s%v", cacheShorturlShorturlPrefix, data.Shorturl)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, shorturlRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Shorturl, data.Url)
	}, shorturlShorturlKey)
	return ret, err
}

func (m *defaultShorturlModel) Update(ctx context.Context, data *Shorturl) error {
	shorturlShorturlKey := fmt.Sprintf("%s%v", cacheShorturlShorturlPrefix, data.Shorturl)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `shorturl` = ?", m.table, shorturlRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Url, data.Shorturl)
	}, shorturlShorturlKey)
	return err
}

func (m *defaultShorturlModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheShorturlShorturlPrefix, primary)
}

func (m *defaultShorturlModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `shorturl` = ? limit 1", shorturlRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultShorturlModel) tableName() string {
	return m.table
}
