// Code generated by goctl. DO NOT EDIT.
// Source: bookstore.proto

package server

import (
	"context"

	"bookstore/bookstore/rpc/bookstore"
	"bookstore/bookstore/rpc/internal/logic"
	"bookstore/bookstore/rpc/internal/svc"
)

type BookstoreServer struct {
	svcCtx *svc.ServiceContext
	bookstore.UnimplementedBookstoreServer
}

func NewBookstoreServer(svcCtx *svc.ServiceContext) *BookstoreServer {
	return &BookstoreServer{
		svcCtx: svcCtx,
	}
}

// 通过书籍名称查找书籍
func (s *BookstoreServer) FindBookByName(ctx context.Context, in *bookstore.FindBookReq) (*bookstore.FindBookReply, error) {
	l := logic.NewFindBookByNameLogic(ctx, s.svcCtx)
	return l.FindBookByName(in)
}
